# Generated by Django 3.2.16 on 2023-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
